# docs https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema

name: Create a bug report
description: Errors and regression reports with complete reproducing test cases and/or stack traces.
labels: [requires triage]
body:
  - type: markdown
    attributes:
      value: "

**PLEASE READ THIS PARAGRAPH - this helps us identify the root cause and fix the issue:**

Many bug reports are often
**USAGE QUESTIONS, NOT BUGS** for APIs that can take some practice to familiarize with,
and which are also tailored towards high quality relational designs that
beginners are sometimes less familiar with.

TODO
"
  - type: markdown
    attributes:
      value: "

**GUIDELINES FOR REPORTING BUGS**

Your bug report should include the following features:

1. a **succinct description of the problem** - typically a line or two at most

2. **succinct code example which reproduces the problem**, otherwise known as a [Minimal, Complete, and Verifiable](https://stackoverflow.com/help/mcve) example.

3. **complete stack traces for errors - please avoid screenshots, and use formatted text inside issues**

4. Other things as applicable: **operating system**, **comparative performance timings** for performance issues.
"
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: To Reproduce
      description: "
Provide your [Minimal, Complete, and Verifiable](https://stackoverflow.com/help/mcve) example here.
      placeholder: "# Insert code here"
      render: python
    validations:
      required: true

  - type: textarea
    attributes:
      label: Error
      description: "
Provide the complete text of any errors received **including the complete stack trace**.
If the message is a warning, run your program with the ``-Werror`` flag:   ``python -Werror myprogram.py``
"
      placeholder: "# Copy complete stack trace and error message here, including SQL log output if applicable."
      value: "\
```

# Copy complete stack trace and error message here, including SQL log output if applicable.

```
"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Versions
      value: |
        - OS:
        - Python:
        - Prefect:
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false

  - type: markdown
    attributes:
      value: "**Happy engineering!**"
